export const MILLISECONDS_PER_DAY = 1000 * 60 * 60 * 24;
export const INDEX = {
  nationCode: 0,
  name: 1,
  summary: 2,
  representativeClaim: 3,
  numOfClaim: 4,
  applicationNumber: 5,
  filingDate: 6,
  numOfRelease: 7,
  releaseDate: 8,
  numOfRegistration: 9,
  registrationDate: 10,
  applicants: 11,
  expiryDateOfDuration: 12,
  contryOfApplicants: 13,
  numOfApplicants: 14,
  investors: 15,
  contryOfInvestors: 16,
  numOfInventors: 17,
  numOfFamilyPatent: 18,
  numOfFamilyContry: 19,
  codeOfFamilyPatent: 20,
  mainIPC: 21,
  IPC: 22,
  legalStatus_KR_JP_EP_CN: 23,
  legalStatus_US: 24,
  numOfReference_B1: 25,
  codeOfReference_B1: 26,
  numOfReference_F1: 27,
  codeOfReference_F1: 28,
  codeOfExaminerReference_F1: 29,
  currentRightHolder: 30,
  originalLink: 31,
  wintelipsKey: 32,
};
