export const MILLISECONDS_PER_DAY = 1000 * 60 * 60 * 24;
export const INDEX = {
  nationCode: 0,
  name: 1,
  summary: 2,
  representativeClaim: 3,
  numOfClaim: 4,
  applicationNumber: 5,
  filingDate: 6,
  numOfRelease: 7,
  releaseDate: 8,
  numOfRegistration: 9,
  registrationDate: 10,
  applicants: 11,
  expiryDateOfDuration: 12,
  contryOfApplicants: 13,
  numOfApplicants: 14,
  contryOfInvestors: 15,
  numOfInventors: 16,
  numOfFamilyPatent: 17,
  numOfFamilyContry: 18,
  codeOfFamilyPatent: 19,
  mainIPC: 20,
  IPC: 21,
  legalStatus_KR_JP_EP_CN: 22,
  legalStatus_US: 23,
  numOfReference_B1: 24,
  codeOfReference_B1: 25,
  numOfReference_F1: 26,
  codeOfReference_F1: 27,
  codeOfExaminerReference_F1: 28,
  currentRightHolder: 29,
  originalLink: 30,
  wintelipsKey: 31,
};
