export const MILLISECONDS_PER_DAY = 1000 * 60 * 60 * 24;
export const INDEX = {
  nationCode: 1,
  name: 2,
  summary: 3,
  representativeClaim: 4,
  applicationNumber: 5,
  filingDate: 6,
  releaseDate: 7,
  registrationDate: 8,
  numOfClaim: 9,
  numOfInventors: 10,
  IPC: 11,
  numOfFamilyPatent: 12,
  numOfFamilyContry: 13,
  applicants: 14,
  numOfApplicants: 15,
  contryOfApplicants: 16,
  inventors: 17,
  legalStatus: 18,
  wintelipsKey: 19,
};
